### ISSUE TITLE
Implement core::fmt::Display for ::crust::error::Error

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/crust#303]
as crust introduced a proper error-type I will now expose that in `RoutingError::Crust(::crust::error::Error)`
however `::crust::error::Error` does not implement `core::fmt::Display`

```
Compiling routing v0.3.8 (file:///home/bbollen/SAFE/rust/routing)
src/error.rs:270:45: 270:62 error: the trait `core::fmt::Display` is not implemented for the type `crust::error::Error` [E0277]
src/error.rs:270             RoutingError::Crust(ref err) => fmt::Display::fmt(err, f),
                                                             ^~~~~~~~~~~~~~~~~
src/error.rs:270:45: 270:62 help: run `rustc --explain E0277` to see a detailed explanation
src/error.rs:270:45: 270:62 note: `crust::error::Error` cannot be formatted with the default formatter; try using `:?` instead if you are using a format string
src/error.rs:270             RoutingError::Crust(ref err) => fmt::Display::fmt(err, f),
                                                             ^~~~~~~~~~~~~~~~~
src/error.rs:270:45: 270:62 note: required by `core::fmt::Display::fmt`
src/error.rs:270             RoutingError::Crust(ref err) => fmt::Display::fmt(err, f),
```
Would crust be okay with implementing that for its error type? 
Routing needs it when Crust would pass an error up on to routing;
eg soon on `::crust::ConnectionManager::new()`

**Comment by vinipsmaker** [comment]
> Would crust be okay with implementing that for its error type?

We need to discuss that. Maybe we just want to use this `Error` type to create custom `io::Error` objects (that was the initial intention, at least).

**Comment by benjaminbollen** [comment]
Yes, but if on construction of ConnectionManager Crust gives a Result<ConnectionManager, What_Error_Will_You_Pass_Routing>?

**Comment by vinipsmaker** [comment]
> Yes, but if on construction of ConnectionManager Crust gives a Result < ConnectionManager, What_Error_Will_You_Pass_Routing > ?

`What_Error_Will_You_Pass_Routing` = `io::Error`

**Comment by benjaminbollen** [comment]
Ok great, I can progress with that.  If it changes at a later change i can accommodate easily enough

**Comment by Fraser999** [comment]
I think it would be better to keep exposing our own `crust::Error` struct.  It's currently exposed because of the file_handler functions (which will probably be used by Vault at least) http://maidsafe.net/crust/master/crust/error/enum.Error.html

I didn't want to return `io::Error` there since that type doesn't properly reflect all the potential failure cases.

If we're exposing `crust::Error` there, I think it would be better to also use that in `ConnectionManager`.

Either way, I'll re-open this as a reminder.  So I think we should either action this issue, or create a new one to replace the current use of `crust::Error` with `io::Error` in file_handler.

**Comment by canndrew** [comment]
For error handling, I'm a big fan of having lots of very specific error types. eg. if three different functions can fail in three different ways they should return three different errors. This makes debugging easier but it also makes code that inspects errors a lot more typesafe because it prevents you from doing things like calling `match` on an error and then calling `unreachable!()` on a branch that you "know can't occur". The downside is you end up having to define lots of error types. I made a syntax extensions a while back that makes defining lots of error types a lot easier: [error_def](https://github.com/canndrew/error_def). Would people be interested in us using this?

**Comment by Fraser999** [comment]
> For error handling, I'm a big fan of having lots of very specific error types.

Me too, within reason.  If a function can reuse existing error values, I think it should.  But if none exist which properly describe the required failure case, then we should define one for it.

> I made a syntax extensions a while back that makes defining lots of error types a lot easier: error_def. Would people be interested in us using this?

Looks very useful to me at first glance, but I guess we'll probably not want to use it for now since it ties us even more to the Nightly channel (https://github.com/canndrew/error_def/blob/master/src/lib.rs#L1-L2).

I guess it'd have to be in crates.io too for us to be able to use it.

**Comment by canndrew** [comment]
> But if none exist which properly describe the required failure case, then we should define one for it.

It's not just a matter of covering all possible failure cases though, it's a matter of covering *only* the possible failure cases. I think we should be more specific than having one crate-level error type. eg. It doesn't make sense for a function that doesn't decode any JSON to be able to return a `JsonDecoderError`.

> but I guess we'll probably not want to use it for now since it ties us even more to the Nightly channel (https://github.com/canndrew/error_def/blob/master/src/lib.rs#L1-L2).
> 
> I guess it'd have to be in crates.io too for us to be able to use it.

It's in crates.io, but yeah it depends on nightly.

**Comment by Fraser999** [comment]
Yeah - I was thinking of crate-level error types.  Where would you see the split being?  mod/function?

I'm still very new to the monadic style of programming, but doesn't having many different error types make that harder?  I suppose we could have a single type used in all public API functions for that crate and internally use whatever additional types we want.

**Comment by canndrew** [comment]
> Where would you see the split being? mod/function?

Function if necessary, although if two different functions have the same set of possible failures they should use the same error type.

> I'm still very new to the monadic style of programming, but doesn't having many different error types make that harder?

Not with `try!` and `error_def!`. The `try!` macro will automatically call `From::from` on an error to cast it to whatever type of error it needs to return. eg. suppose we have these functions:

    fn read_file(p: &Path) -> Result<Vec<u8>, io::Error>;
    fn decode_json(encoded: &[u8]) -> Result<Foo, JsonDecodeError>;

and we want to combine them to read and decode a file. We can do that easily with try:

    fn parse_file(p: &Path) -> Result<Foo, ParseFileError> {
        let data = try!(read_file(p));    // upcasts io::Error -> ParseFileError
        let foo = try!(decode_json(&data[..]));    // upcasts JsonDecodeError -> ParseFileError
        foo
    }

But we need to implement `From` for our new `ParseFileError` type so that `try!` knows how to do the casting.

    impl From<io::Error> for ParseFileError {
        ...
    }

    impl From<JsonDecodeError> for ParseFileError {
        ...
    }

With `error_def!` though you don't need to write these impls manually, you'd just define your error like this:

    error_def! ParseFileError {
        Io { #[from] cause: io::Error }
            => "An IO error occured reading the file" ("The error was {}", cause),
        JsonDecode { #[from] cause: JsonDecodeError }
            => "Failed to parse JSON data" ("Json error was: {}", cause),
    }

And it will automatically generate `From` impls using the members that are marked #[from]. It will also automatically generate impls for `Error`, `Debug` and `Display` (which is why I originally brought this up in this thread).

**Comment by canndrew** [comment]
oops, wrong button.

**Comment by vinipsmaker** [comment]
I agree with @canndrew in this one.

And it's worth remembering that the custom error was initially created just so we could create custom `io::Error`s and nothing else. Somewhere in the journey it started to be used in other abstractions.

**Comment by Fraser999** [comment]
@canndrew - I can't say I'm totally convinced.  While `try!` is succinct and useful for code clarity, it's not always what we want (and it's a pain when using the debugger).  I was thinking more about function chaining when I mentioned monadic programming; so in your example, something like:

    read_file(p).and_then(|data| decode_json(&data[..]))

Having `read_file` and `decode_json` returning different types makes this style harder since we need to explicitly change the types to match throughout the chain I think (and also to match the `read_and_decode` function's return).  If I'm wrong on that, then I could be persuaded that function-level error types is better than crate-level.

@vinipsmaker I agree that that is how the custom error started life, but I'd expected most or all of our projects to fully define and use their own error types once we got more used to the Rust paradigms.

**Comment by Fraser999** [comment]
I spoke with @dirvine earlier.  He's tried out running with per-function/module error types (in Routing specifically) and came to the conclusion that per-crate works best, although for different reasons to mine.

**Comment by canndrew** [comment]
>  Having `read_file` and `decode_json` returning different types makes this style harder since we need to explicitly change the types to match throughout the chain I think (and also to match the `read_and_decode` function's return). If I'm wrong on that, then I could be persuaded that function-level error types is better than crate-level.

You're not wrong, except that if you use `try!` instead you get the error conversion automatically:

    let data = try!(read_file(p));
    decode_json(&data[..]);

IMO breaking code into separate statements like this makes it a bit easier to read. This code does the same thing except that you have to wrap it in a closure if you don't want to exit the function on an error (although [try blocks](https://github.com/rust-lang/rfcs/pull/243) should fix that).

> and it's a pain when using the debugger
> ...
>  although for different reasons to mine.

Can you elaborate on these at all?

Overall I agree with you though. Without macros to make it easier (which would force us to stay on nightly) having super-specific error types is more trouble than it's worth.

**Comment by Fraser999** [comment]
I've not come across the try blocks discussion - I'll need to read it properly, but it seems promising.  As for `.and_then` vs two lines, I guess I'm not sold on either approach yet.  I am under the (maybe wrong) impression that the monadic/continuations approach is more desirable in Rust.  I too find the two lines easier to read, but I'm not sure if that's down to my time with C++ and that the other style will become more readable to me over time.

My previous experience with debugging code wrapped in any macro has been that I can't!  Whenever execution hits the macro, the debugger loses track of the actual line being executed - for `try!` it invariably took me to line 2 of whatever file was being debugged, which would be the second line of the copyright notice :)

As for @dirvine's experience with multiple `Result` types, I'd best let him explain - I can't say I fully understood his points.

**Comment by ustulation** [comment]
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.
