### ISSUE TITLE
Any way to get `TcpSocket`?

### ISSUE THREAD

**Issue by dpc** [maidsafe/crust#362]
It seems to me that it should be possible for user of crust to get a `TcpSocket` or `UdpSocket` from the `Connection` and write/read directly, instead of using `Service::send` and `Event(NewMessage)`.

I wanted to use crust connections inside mioco which would deal with read/write eventing for me.

**Comment by inetic** [comment]
Hi `dpc`, thanks for the suggestion. I personally have yet to have a better look at `mioco`, coroutines are certainly something we would love to support, there are few big fans here ( @vinipsmaker  :) ).

`Connection` structure currently serves as just an ID, it would be nice to have the actual socket wrapped in it, but using it from outside of the Crust library may not be as straight forward it appears. It is because we plan to use the socket for sending auxiliary data along user's data to communicate NAT traversal information. Currently this auxiliary "channel" is not used as we've managed to communicate all such information during a "handshake", but we'd like to keep this option open.

Perhaps an API such like this could be used instead?

```
TcpOrUdpSocket s = service.release(connection);
```

**Comment by dpc** [comment]
Oh, I see. I guess if `Service::send` is non-blocking, I would still be fine.

**Comment by inetic** [comment]
I'm sorry for the delay. Are you suggesting that `Service::send` function should be made non-blocking? If so, the function currently is such. Where you may hit a problem is that currently this function doesn't notify back user about its completion, which is something we should have a look into.

**Comment by dpc** [comment]
I need to try it in practice. I don't think I need a notification back, as long as queuing requests can't fail, or block.
