### ISSUE TITLE
Remove duplicate connections

### ISSUE THREAD

**Issue by vinipsmaker** [maidsafe/crust#551]
If there is more than one connection against the same peer (identified by `PublicKey`), we should drop redundant connections.

Most likely this task will need a RFC.

An example algorithm (not recommending this route, as I'd do it by the RFC process and not here on the issue tracker):

1. Elect a `master` (e.g. whoever has the lower `PublicKey`).
2. `master` gracefully closes redundant connections. It will only shut the send ending and wait for all incoming messages and shutdown ack arrive (so we do not lose any message).
  - Measurement of transfer speed could be used to choose which connection to close. Although this is a difficult one as transfer speed might change at the time we measure (other network traffic...).
  - We could favor LAN addresses (and address which don't need NAT traversal) over global addresses.
  - Lots of heuristics to debate.

**Comment by dirvine** [comment]
I suspect this issue may become redundant with some refactoring. Udp rendezvous connect should I feel only do one connection. Tcp will be the same if we implement hole punch there properly (as one connect is guaranteed dropped as per the paper https://www.goto.info.waseda.ac.jp/~wei/file/wei-apan-v10.pdf ). 
Doing this may be good as some folk may wish to make multiple connections to peers and bannign it may be a problem. So if we can get it so that there is only one connection when requested and if we get multiple requests we get multiple connects it would seem preferred I think

**Comment by vinipsmaker** [comment]
> Udp rendezvous connect should I feel only do one connection.

1 TCP connection + 1 uTP connection to the same peer are redundant in respect to each other (TCP and uTP). Certainly it is open to debate whether want to drop these extra connections that use different protocols.

**Comment by dirvine** [comment]
Yes agreed, I suspect we can in crust do something like a speed test and keep the most efficient, however it may change over time (the efficiency). I imagine until we have utp outperforming tcp we choose tcp in this situation for now.

**Comment by ustulation** [comment]
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.
