### ISSUE TITLE
Need to ignore incompatible nodes.

### ISSUE THREAD

**Issue by Bluebird45** [maidsafe/crust#732]
Hi, I've noticed a problem that qualifies as a bug. I describe it here: https://forum.safenetwork.io/t/community1-test-network-is-alive-join-us/9337/77?u=bluebird The community1 network is running safe_vault 0.8.1

I'm not sure but I understand that newer versions of the software will ignore older versions, and not have any problems as a result of older, incompatible binaries trying to connect. However, it appears that in the opposite situation, of newer binaries (launchers or vaults) trying to connect to a network where an older version is the default, that the older binaries are <b>not</b> ignoring these attempts to connect, and the result is instability on the network. Is there at least a workaround for this until a patch can be applied?

**Comment by Viv-Rajkumar** [comment]
This shouldn't really be any different between old connecting to new or new connecting to old. It's just a hash check of the field from the crust config file and if the `network_name` field doesn't match then the incoming connection is dropped with the message [Incompatible protocol version](https://github.com/maidsafe/crust/blob/master/src/connection.rs#L486)

As you mentioned a few posts later in the forum thread, vault binaries weren't released on Thursday and this error isnt limited to vaults. This is just a handshake check done while bootstrapping for both vaults and clients(launcher).

This could have occurred if someone ran Launcher released Thursday against the community network which uses a different crust version or if someone just did not pass the correct `network_name` and just updated the `hard_coded_contacts` in the config file.

Is the issue here just that the log file is getting spammed with this message? you can maybe just disable logging from crust in that case which should keep the log files smaller but not sure if this was the only isse here.

**Comment by Bluebird45** [comment]
The log file is getting spammed, grows to huge size, gets truncated (so i see only a few hours worth) and vault restarting. I'm not sure whether the restarts are connected to the log spamming.

How would you suggest to disable the messages?

**Comment by Viv-Rajkumar** [comment]
yeh the restarts are what I'm wondering about. That would happen if the Routing table collapses(goes below size 8). You want to aim to keep network size at a minimum of > `GROUP_SIZE`

> How would you suggest to disable the messages?

for this since its an error message from crust, to disable it we'd prolly need to disable crust logging pretty much. You will have a `log.toml` file next to `safe_vault` binary which if you update to:

```
[appender.async_console]
kind = "async_console"
pattern = "%l %d{%H:%M:%S.%f} [%M #FS#%f#FE#:%L] %m"

[[appender.async_console.filter]]
kind = "threshold"
level = "info"

[appender.async_file]
kind = "async_file"
path = "Node.log"
pattern = "%l %d{%H:%M:%S.%f} [%M #FS#%f#FE#:%L] %m"
append = false

[root]
level = "error"

[[logger]]
name = "routing"
level = "debug"
appenders = ["async_console", "async_file"]

[[logger]]
name = "safe_vault"
level = "debug"
appenders = ["async_console", "async_file"]
```

should have logs from crust ignored in both the console logs and file.

**Comment by Bluebird45** [comment]
This is something that i am unclear on:#

The launcher presumably connects to the hard-coded vault on port 5483. If I block port 5483 at the firewall, the error messages keep coming. Why is that, and is it really a launcher that is to blame?

**Comment by Bluebird45** [comment]
The solution that you propose suppresses all crust messages, which ruins my statistical collection. Is there a way to turn off that particular message only?

**Comment by Bluebird45** [comment]
I just ran a compile of the master branch of safe_vault and I see thousands of these "Incompatible protocol" messages in Node.log, and I know there is only one other vault on the test network (community1 and both machines are hard-coded contacts), which happens to be running the testnet3 binary. What is worth reporting is that: 1. the problem affects the current binary when an older binary is trying to connect to it, and 2. this appears to be the same bug as originally reported above.

**Comment by ustulation** [comment]
This crate had a major re-write/re-design. Please raise an issue again if required as almost everything in the library and the way it handled things have changed. Closing this.
