### ISSUE TITLE
Discussion - Usage of unwraps/expects etc in production

### ISSUE THREAD

**Issue by ustulation** [maidsafe/crust#736]
This is mainly to formalise situations where we can and cannot use unwraps (or things that cause panic) in production (along with alternatives if any).

The cases where we tend to have unwraps
1) locking a mutex
2) spawning a thread
3) joining a thread
4) A logic like this -> You put something in a `Some()` right at construction and later do `take().unwrap()` because we know it will be a logical fallacy to have ​_None_​ there. A use case for this is: there are situations where we don't want to `clone` (or cannot `clone/copy`) an object and want to hand it to other. So you wrap it in an `Option::Some` and do a `take()` to move it out. Search for `option dance` idiom in rust.

**Comment by ustulation** [comment]
The list is of-course grow-able, so if anybody has any other situation that needs discussion, we will append to that list. Against each point we need to finally agree on whether to use `unwrap()` OR use `expect()` OR use some other form of panic (with details of what and how to use this) OR use some form of error handling (again with details of what and how to use it).

**Comment by canndrew** [comment]
In all these cases the best option would be to use `unwrap_result!`/`unwrap_option!`. These behave like `unwrap`/`expect` except they print the location in the source where the panic occurred. For cases 1, 2 and 3 `unwrap_result!` will print the `Err` value that was unwrapped (meaning it's not necessary to add our own string explaining what the error was). For case 4 `unwrap_option` takes an explanation string like `expect`.

**Comment by ustulation** [comment]
Our unwrap macros:
================
Pros:
--------
1) Getting the exact line number
2) error printouts and decoration
3) optional explanation in case of `unwrap_option`
4) have actually proven to be very helpful in the past, especially during testing and maintaining codes written by others and also catching logical bugs in the code.
Cons:
--------
1) Only good for main thread. If inside another thread, it prints the line number corresponding to the entry point of the thread (I might be wrong here but remember running into this)
2) I find the name too long - if it is entirely for the purpose of convenience it should be as un-intrusive a name as possible. So maybe something `ur!` and `uo!` are better because if we do vote to keep these macros, their uses will be wide and pretty standard and `ur!` should just easily _get into our systems_. It will make the actual code more readable and succinct.

std unwrap/expect:
================
Pros:
--------
1) They are in std and expect allows use to write custom strings. (Sorry cant think of any more pros - pls free to add).
Cons:
--------
1) Using custom strings to track errors is verbose, redundant (all errors do a debug print anyway)  and affects code readability (as panics wont happen most of the time, but we read that code everyday and it quickly becomes irritating). Also it has to be carefully orchestrated because string literals are not language obligations but user choices. The review process might have some debates on the correct string (as more ppl start contributing) and hence stretch longer and is extra maintenance hassle.
2) The reason to have those macros were to overcome the limitations of these. So all the advantages there are disadvantages here. These are not doing anything different than the above macros otherwise - both categories panic, and we are taking about cases where it is _ok_ to panic. If we _don't want_ to panic then that is a different issue.

**Comment by canndrew** [comment]
> 2) I find the name too long - if it is entirely for the purpose of convenience it should be as un-intrusive a name as possible. So maybe something ur! and uo! are better because if we do vote to keep these macros, their uses will be wide and pretty standard and ur! should just easily get into our systems. It will make the actual code more readable and succinct.

I wrote the [unwrap crate](https://crates.io/crates/unwrap) so that we can just use `unwrap!` instead of `unwrap_result!` and `unwrap_option!`. This also has the advantage of making `maidsafe_utilities` smaller (I'm not a fan of having a miscellaneous dumping ground crate - I'd rather just have a few small crates).

`ur!` and `uo!` would be confusing to someone who's not familiar with our code. I don't know how much of an issue we consider that to be.

**Comment by canndrew** [comment]
> 1) Only good for main thread. If inside another thread, it prints the line number corresponding to the entry point of the thread (I might be wrong here but remember running into this)

The problem is that if use them inside a macro they will print the location of the outer macro invocation. Eg this:

    thread!("I'm a thread", || {      // <-- This line number gets printed
        ...
        unwrap_result!(Err("oh no")); // <-- Instead of this one
    })

If you call a function inside of the `thread!` then any unwraps inside it will print the correct location.

So, worst case scenario, you get the correct file and function but wrong line number.

**Comment by ustulation** [comment]
> This also has the advantage of making maidsafe_utilities smaller (I'm not a fan of having a miscellaneous dumping ground crate - I'd rather just have a few small crates).

Let's not digress from the topic. (For e.g. I am not a fan of multiple crates if all we are doing at the end of the day is including every one of them in each or most of our crates. We are writing code for ourselves). But this topic is not about that and discussing opinions on everything will dilute the main purpose.

**Comment by ustulation** [comment]
> The problem is that if you use them inside a macro they will print the location of the outer macro invocation
Ah, good to know.

**Comment by canndrew** [comment]
> For e.g. I am not a fan of multiple crates if all we are doing at the end of the day is including every one of them in each or most of our crates. We are writing code for ourselves.

Well, I disagree. The argument for using `.unwrap()`/`.expect()` is that they're standard. If we split `unwrap_result!`/`unwrap_option!` into their own crate then they can be used by people outside of MaidSafe and they stand a chance of becoming semi-standard. We don't roll our own endianess-swapping code, we use the same `byteorder` crate that everyone else does. Wouldn't it be good if we could use the same unwrapping macros as everyone else aswell? Aren't you glad @BurntSushi didn't keep his byteorder code hidden away inside whatever project he was using it for? Plus, by allowing more people to use these libraries we allow them to give us feedback and PRs - [like what happened yesterday](https://github.com/maidsafe/get_if_addrs/pull/24).

It's extremely little effort to split things into separate libraries - an extra line in `Cargo.toml` and an extra `extern crate ...` - so let's keep separate things in separate crates where they belong.

And this isn't completely off-topic because if we want to use unwrapping macros (which seems to me to be the only sensible choice) then we need to decide whether to keep them in `maidsafe_utilities` or not.

**Comment by canndrew** [comment]
> If inside another thread, it prints the line number corresponding to the entry point of the thread

Fix: https://github.com/maidsafe/maidsafe_utilities/pull/65

**Comment by afck** [comment]
My main headaches are:
* Lots of crates depend on (often different versions of) maidsafe_utilities just to use these macros.
* I want to use Clippy, but that requires the checked-in code to be in a state where Clippy passes, i. e. all lints must be either followed or `allow`ed. (Note, however, that `option_unwrap_used` and `result_unwrap_used` are `allow`ed by default, so the question is whether we want to explicitly `deny` them.)

So: I'm happy with just switching to the unwrap crate everywhere and using the macros in all four cases - then we _would_ probably want to `deny` the lints - or with just `allow`ing the `unwrap()` method for these uses, since that's the standard way to do it, and it wouldn't require any additional dependency.

(Either way that shouldn't be considered a free pass to unwrap everywhere, of course, and in all but the cases discussed here, errors need to be properly handled.)

**Comment by Fraser999** [comment]
My strong preference is to use macros exclusively for unwrapping.  I agree with the pros listed by Spandan above.  As for the cons, I'm not concerned that it's not in the standard (it's a better solution in my opinion, and the standard is still evolving) and the length of the names is not a problem to me.  I far prefer `unwrap_result!` to `ur!` since `ur` isn't even close to something recognisable by an uninitiated reader.  I'd suggest that debating variables/functions/macros' names would be best left to another thread too maybe?

Having not actually used Andrew's crate, I have to say that it seems to provide the optimal solution.  We're provided with just a single, terse macro `unwrap!` which is also capable of taking an explanatory string, but doesn't require it (as `unwrap_option!` currently does).

My main concern with this is simply that it's another dependency.  I agree with Spandan's position on these generally, and while I know that it's not meant to be discussed as part of this thread, it does affect my preference.

My ideal would be to have Andrew's `unwrap!` code moved or duplicated into maidsafe_utilities and have a policy to use that macro *everywhere* we want to unwrap a `Result` or `Option` (production/test/benchmarks/doc-examples all treated the same).  Second best would be to use the existing macros from maidsafe_utilities.  Third best would be to remove the macros from utilities and use Andrew's crate.  All of these are decent options to me and I don't have a massively strong preference between them.  By far the worst option is using the `unwrap()` and/or `expect()` functions.

**Comment by maqi** [comment]
can we have the unwrap_result/unwrap_option macro not to take the string msg?

**Comment by afck** [comment]
@maqi: I think in the unwrap crate these are already optional, and they allow argument formatting. (Right, @canndrew?)

And I'd really prefer to keep it as a separate crate rather than merging it into maidsafe_utilities: We often have the problem that three different versions of maidsafe_utilities get compiled because we have to do a minor version change whenever we change the API of just _one_ utility ...

**Comment by maqi** [comment]
@afck : sry, my fault, unwrap_result doesn't take a string msg, but unwrap_option needs one. my question is can we have unwrap_option taking optional msg?

meanwhile, if we do decide to go the macro way, I also think make it a separate crate will be better wrap it inside maidesafe_utility (if there is no equivalent crate available yet)

**Comment by afck** [comment]
That's what I mean: I'm in favour of using Andrew's unwrap crate instead of the maidsafe_utilities macros: https://crates.io/crates/unwrap
It does all that.

**Comment by dirvine** [comment]
In the case mentioned in the OP 
> A use case for this is: there are situations where we don't want to clone (or cannot clone/copy) an object and want to hand it to other. So you wrap it in an Option::Some and do a take() to move it out. Search for option dance idiom in rust.

Is this not misuse anyway ?  I think this is where cell/refcell should be used 
https://killercup.github.io/trpl-ebook/trpl-2015-09-26.html#sec--choosing-your-guarantees
http://doc.rust-lang.org/std/cell/

**Comment by canndrew** [comment]
@dirvine 
No, he's talking about, for example, when you need to move out of something that implements `Drop`.

**Comment by ustulation** [comment]
Decision on this has been reached. Pls refer to [style guide](https://github.com/maidsafe/QA/blob/master/Documentation/Rust%20Style.md).
